# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-epl
canonical: http://fhir.ch/ig/ch-epl
url: http://fhir.ch/ig/ch-epl/ImplementationGuide/ch.fhir.ig.ch-epl
name: CH_EPL
title: "CH EPL (R5)"
description: Implementation Guide CH EPL (R5)
status: active
license: CC0-1.0
copyright: CC0-1.0
# ignore information about deprecated item, see https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/http.3A.2F.2Fhl7.2Eorg.2Ffhir.2FValueSet.2Fjurisdiction.20deprecated.20warnin
# jurisdiction: urn:iso:std:iso:3166#CH
date: 2023-11-10
version: 1.0.0-ballot
fhirVersion: 5.0.0
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Federal Office of Public Health FOPH
contact:
  - name: Federal Office of Public Health FOPH
    telecom:
      - system: url
        value: https://www.bag.admin.ch/bag/en/home/das-bag/kontakt-standort.html

dependencies:
#  ch.fhir.ig.ch-core: 4.0.1
  hl7.terminology.r5:
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    version: 6.3.0

pages:
  index.md:
    title: Home
  idmp.md:
    title: IDMP Standard ISO 11615
  authorised-medicinal-product.md:
    title: Datasource Authorised Medicinal Product
  spezialitaetenliste.md:
    title: Dataexport FOPH Spezialitätenliste
#  usecase-german.md:
#    title: Use Cases
  cuprior.md:
    title: Cuprior
  entocort.md:
    title: Entocort
  estalis.md:
    title: Estalis 
  keytruda.md:
    title: Keytruda
  paxlovid.md:
    title: Paxlovid
  triogen.md:
    title: Triogen 
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog

menu:
  Home: index.html
  Documentation:
    ISO IDMP: idmp.html
    Datasource: authorised-medicinal-product.html
    Spezialitätenliste: spezialitaetenliste.html
#  Use Case:
#    German: usecase-german.html 
  Examples: 
     Cuprior: cuprior.html
     Entocort: entocort.html
     Estalis: estalis.html
     Keytruda: keytruda.html
     Paxlovid: paxlovid.html
     Triogen: triogen.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html

# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true
  path-expansion-params: '../../expansion-params.json' # for using SNOMED CT Swiss Extension
  special-url:
    - urn:oid:0.4.0.127.0.16.1.1.2.1 # edqm-standard-terms
    - urn:oid:0.4.0.127.0.16.1.1.2.2 # edqm-pharmaceutical-dose-form
    - urn:oid:0.4.0.127.0.16.1.1.2.3 # edqm-combined-pharmaceutical-dose-form
    - urn:oid:0.4.0.127.0.16.1.1.2.4 # edqm-combined-term
    - urn:oid:0.4.0.127.0.16.1.1.2.5 # edqm-combination-packaging
    - urn:oid:0.4.0.127.0.16.1.1.2.6 # edqm-route-of-administration
    - urn:oid:0.4.0.127.0.16.1.1.2.7 # edqm-packaging
    - urn:oid:0.4.0.127.0.16.1.1.2.11 # edqm-unit-of-presentation
    - http://standardterms.edqm.eu # edqm
    - urn:oid:1.2.276.0.76 # ema-rms
    - http://spor.ema.europa.eu/v1/lists/100000000004 # ema-domain
    - http://spor.ema.europa.eu/v1/lists/100000073343 # ema-shelf-life-type
    - http://spor.ema.europa.eu/v1/lists/200000003186 # ema-intended-effect
    